server:
  port: 8000

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangyyang/srpingcloud-config
          username: userName
          password: userPassword
          default-label: master


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka.server:8801/eureka/,http://eureka.server.assistant:8802/eureka/

